# Generated by Django 4.2.3 on 2023-07-26 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auto_insurance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autopolicydocument",
            name="mileage",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="autopolicydocument",
            name="rating",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autopolicydocument",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="autopolicydocument",
            name="vin",
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="autopolicydocument",
            name="year",
            field=models.PositiveIntegerField(),
        ),
    ]
