# Generated by Django 4.2.3 on 2023-07-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_insurance', '0003_autocoveragedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoCoverageDetails',
            new_name='AutoCoverageDetail',
        ),
    ]
