# Generated by Django 4.2.3 on 2023-07-30 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auto_insurance", "0004_rename_autocoveragedetails_autocoveragedetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autocoveragedetail",
            name="auto_documents",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auto_insurance.autopolicydocument",
            ),
        ),
    ]
