name: Create Cloud Infrastructure

on:
  push:

jobs:
  # build-test-deploy:
  #   uses: ./.github/workflows/build-test-deploy.yml
  #   secrets: inherit

  infrastucture-creation:
    # needs: build-test-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: authenticate with gcp
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init 
        working-directory: _terraform/

      - name: Terraform Workspace
        run: terraform workspace new ${{ github.ref_name }} || terraform workspace select ${{ github.ref_name }}
        working-directory: _terraform/

      - name: Terraform Plan
        run: terraform plan -var="project_id=${{ secrets.ADMIN_PROJECT }}" -var="image_tag=europe-west2-docker.pkg.dev/${{ secrets.ADMIN_PROJECT }}/dynamic/config:latest" -lock=false -input=false
        working-directory: _terraform/

      - name: Terraform Apply
        run: terraform apply -var="project_id=${{ secrets.ADMIN_PROJECT }}" -var="image_tag=europe-west2-docker.pkg.dev/${{ secrets.ADMIN_PROJECT }}/dynamic/config:latest" -auto-approve -lock=false  -input=false
        working-directory: _terraform/